name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Production Dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Development Dependencies
      run: |
        pip install -r requirements_dev.txt

    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2